title: Time Series Modelling with Unobserved Components
description: The official book's website
baseurl: "/ucmbook"
url: "https://your-username.github.io"
remote_theme: aksakalli/jekyll-doc-theme
markdown: kramdown
highlighter: rouge
