title: Time Series Modelling with Unobserved Components
description: The official book's website
baseurl: "/ucmbook"
url: "https://matteopelagatti.github.io"
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge
collections:
  pages:
    output: true
    permalink: /:path/
navigation:
  - title: Home
    url: /
    nav_order: 1
  - title: Data
    url: /data/
    nav_order: 2
  - title: Code
    url: /codes/
    nav_order: 3